#!/usr/bin/env bash
# first test if ghc is on our path...
getghc () {
    GHC=$(command -v ghc);
    if [ -x "$GHC" ]; then
        echo "Looks like you have this: $GHC on the path";
        $GHC --version;
    else
        echo "No ghc command found on path"   
    fi
}

setghc () {
    GHCDIRS=($(ls -d ../ghc* | sed -e 's|.*/||'))
    echo "Choose one of these ghc installs to activate:"
    select foo in "${GHCDIRS[@]}"; do
        ghcpath=$(realpath $(pwd)/../$foo/bin)
        echo $ghcpath
        export PATH=${ghcpath}:$PATH
        getghc;
        echo "May the lambdas flow..."
        break;
    done
}
